# Generated by Django 4.2.7 on 2023-11-20 12:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_department_image_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
